### ISSUE TITLE
Player is able to jump while crouching, causing clipping issues in certain situations

### ISSUE THREAD

**Issue by MichaelFar** [ProjectCGC/Hyponic-Biotic-Outbreak#35]
Description:

The player is not forbidden to jump while crouching. In certain low-ceiling areas, such as vents or under desks, the player is still able to jump causing camera clipping issues.

Steps to reproduce:

1. Using Unreal 5.3.2, load Hyponic-Biotic-Outbreak

2. Select the level L_Demo_Pre_Alpha and click the play icon on the header bar

3. Once controlling the player pawn, navigate to a low ceiling area, such as the nearby arches

4. Hit the 'jump' key (as of writing this is 'spacebar')

Expected results:

Player is either forbidden from jumping while crouching, or the player is prevented from clipping their camera into the ceiling

Actual results:

Player is able to jump while crouching, the camera clips into the ceiling geometry

Please see attached video:

https://github.com/user-attachments/assets/2443b707-710b-4ad0-b70d-e6d39822b735

**Comment by ElsFouche** [comment]
This issue was expected. During the rapid prototyping process for the player controller and pawn, the default jump action provided by the character movement component was used. This default jump does come with built in state checking to prevent infinite jumping e.g. while airborne however the player controller utilizes different states than those provided by the character movement component. This results in the 'can jump' bool not being set appropriately by custom states such as the player crouching or going prone. 

Solution: add state checking prior to allowing jump. 

Why wasn't this implemented sooner considering how easy it is? - Due to the requirements for our player focusing more on vaulting low walls and clambering up onto certain objects, standard jumping was never an intended movement mechanic, thus no state checking for jumps were added.

**Comment by ElsFouche** [comment]
State checking prior to jumping added in PR 39 - "Player can now dive into crawling state." Issue closed.
