### ISSUE TITLE
Enemy AI stalls when the player is on the otherside of a door threshold

### ISSUE THREAD

**Issue by MichaelFar** [ProjectCGC/Hyponic-Biotic-Outbreak#41]
Description:
The enemy AI does not give up pursuing the player across door thresholds despite having no valid path to the player

Steps to Reproduce:

1. Using Unreal 5.3.2, load Hyponic-Biotic-Outbreak

2. Select the level L_Demo_PreAlpha and click the play icon on the header bar

3. Pick up the key close to the player start point

4. Navigate to the room in front of the player

5. Open the door to the left with the key

6. Approach the enemy AI until the enemy pursues the player

7. Navigate back to the previous room while the AI continues pursuit

8. Stand just on the other side of the door

Expected Results:

AI is unable to cross the threshold, but the AI also chooses a different valid path or switches states

Actual Results:

The enemy will endlessly remain in the pursuit state until the player elects to exit the AI's line of sight

See video link:

https://drive.google.com/file/d/1P01xLCIPCafirOxAHLcvctOMHJuW0Awg/view?usp=drive_link

**Comment by ElsFouche** [comment]
This issue was caused by navigation mesh data not being generated due to closed doors. Two solutions were explored: nav mesh link proxies and disabling doors from nav mesh data generation calcuations. 
- Nav mesh link proxies worked very well for creating pseudo-connections between isolated navigation areas and are a useful solution in many contexts but were determined to be inefficient with regards to doors. AI navigation successfully accounts for non-navigable terrain e.g. walls even when there is valid navigation mesh. This means nav mesh link proxies add a layer of unnecessary complexity to level creation.
- Disabling nav mesh generation for doors incurs less complexity cost as well as having smaller memory overhead. No issues with AI navigation with regard to closed doors has been observed - further testing is required to confirm this fully.
